version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8082:80"